GET http://localhost:3000/users
?limit=10
&page=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoibWFya0Bkb2UuY29tIiwiaWF0IjoxNzYyODg4Nzk5LCJleHAiOjE3NjI4OTIzOTksImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.yCuhGotaMgkgqPRmfheLYZG1KVsu069t-OdfTdL2N9E
