POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImlhdCI6MTc2Mjg4NTczMCwiZXhwIjoxNzYyOTcyMTMwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0._eh-_1KJ5aFhYpI24kNrLZtT4Wgst02dBGTmNZQNyU4"
}